project:
  type: website

website:
  title: "Home"
  navbar:
#    right:
#      - icon: github
#        href: https://github.com/paulhirschi
#      - icon: linkedin
#        href: https://www.linkedin.com/in/paulhirschi1
#      - icon: twitter
#        href: https://twitter.com
    left:
      - posts.qmd
      - projects.qmd
      - about.qmd
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css



