project:
  type: website

website:
  title: "Paul's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/paulhirschi
      - icon: linkedin
        href: https://www.linkedin.com/in/paulhirschi1
#      - icon: twitter
#        href: https://twitter.com
format:
  html:
    theme: sandstone
    css: styles.css



